services:
  - type: web
    name: bot-instagram-mindfulness
    env: node
    buildCommand: npm install && pip install -r requirements.txt
    startCommand: npm start
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: INSTAGRAM_USERNAME
        sync: false
      - key: INSTAGRAM_PASSWORD
        sync: false